### ISSUE TITLE
Not able to diagonalise the Spin 1/2 Hamiltonian larger than 24 using Lanczos Method

### ISSUE THREAD

**Issue by hcut** [QuSpin/QuSpin#566]
Hello QuSpin,

I am not able to diagonalize a spin 1/2 Hamiltonian for dimension larger than N=24 at my workstation (26 core /2 threading per core, 512 RAM).

     Hermiticity check passed!
     Traceback (most recent call last):
     File "/home/chumbak/work/hida/ed/ed_mgn_ftlm.py", line 173, in <module>
     run_computation() 
     File "/home/chumbak/work/hida/ed/ed_mgn_ftlm.py", line 127, in run_computation
     E,V,lv = lanczos_full(H_wrapped,r,m,eps=1e-8,full_ortho=True)
     File "/home/chumbak/anaconda3/lib/python3.9/site-packages/quspin/tools/lanczos/_lanczos_utils.py", line 207, in lanczos_full
     q,_ = _np.linalg.qr(Q[:m].T)
     File "<__array_function__ internals>", line 5, in qr
     File "/home/chumbak/anaconda3/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 975, in qr
     results = lapack_routine(m, mc, mn, q, max(1, m), tau, work, lwork, 0) 
     OverflowError: signed integer is greater than maximum

Could you please help me out here ?

**Comment by HamidArianZad** [comment]
Hi,

I have the same problem with Lanczos method to diagonalize a two-leg ladder with more than 24 spins in my workstation.
My system has 48 gig RAM Corei7 10-th gen.
However, I am able to diagonalize the same model with 28 spins (maybe up to 32 spins is also possible) by using ALPS package.
Could you resolve the problem in QuSpin?

**Comment by quantum-magnet** [comment]
No, Hamid.

**Comment by speotta** [comment]
We the new version of Quspin this problem should have been solved.
See this other issue: https://github.com/QuSpin/QuSpin/issues/596
I had a similar problem, but now the code works fine with the new version.

**Comment by quantum-magnet** [comment]
ok, I will check this out

**Comment by mgbukov** [comment]
closing due to lack of activity

**Comment by speotta** [comment]
The problem has been solved by updating to the latest version for me. Are you using the latest version of QuSpin?

**Comment by speotta** [comment]
As you can see from this [paper](https://link.aps.org/doi/10.1103/PhysRevResearch.5.043215) we have done pretty large systems but usually with small number of particles. You should contact the person actually running the simulations: Koushik Swaminathan (koushik.swaminathan@aalto.fi), he can give you mode details.
Initially the workaround mentioned in issue #596 solved the problem and then with the new version the work around was not needed anymore.

**Comment by speotta** [comment]
This sounds like a different problem. You should open a new issue and include the source code to enable others to recreate the problem.
