### ISSUE TITLE
hamiltonian.evolve with iterate=True and stack_state=True fails when evolving multiple states in parallel

### ISSUE THREAD

**Issue by jaredjeya** [QuSpin/QuSpin#654]
**Describe the bug**
Using hamiltonian.evolve with iterate=True and stack_state=True fails when evolving multiple states in parallel (i.e. parameter v0 is 2-dimensional).

**To Reproduce**
```python3
import numpy as np
from quspin.operators import hamiltonian
from quspin.basis import spin_basis_1d

N = 6
n_state = 10
times = np.linspace(0, 1, 11)

basis = spin_basis_1d(N)
static = [["x", [[1.0, i] for i in range(N)]]]
H = hamiltonian(static, [], basis=basis, dtype=np.float64)

states = np.random.random(size=(basis.Ns, n_state))
states /= np.linalg.norm(states, axis=0, keepdims=True)
iter_states = H.evolve(states, 0.0, times, stack_state=True, iterate=True)

for state in iter_states:
	pass
```

**Expected behaviour**
`state.shape == (basis.Ns, n_state)` and the code runs without issue.

**Actual behaviour**

```python3
Traceback (most recent call last):
  File "<ipython-input-6-3e2b33ed361d>", line 17, in <module>
    for state in iter_states:
  File "C:\ProgramData\Miniconda3\envs\general_3_10\lib\site-packages\quspin\tools\evolution.py", line 413, in _evolve_iter
    y_fmt = _format_output(v0,*output_args)
  File "C:\ProgramData\Miniconda3\envs\general_3_10\lib\site-packages\quspin\tools\evolution.py", line 348, in _format_output
    yout = y[:Ns].astype(_np.complex128).reshape(shape0)
ValueError: cannot reshape array of size 64 into shape (64,10)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: `0.3.7 omp_py310hae804e4_0 weinbe58`

**Comment by jaredjeya** [comment]
I think the issue is in the _format_output function, which is passed the original shape0 and not shape0_ravelled, and is therefore confused about the size of the vector which is being evolved. I could submit a pull request to fix this if I find time. This happens with iterate=True also.

**Comment by jaredjeya** [comment]
Ok - I'd like to try and fix this but I can't work out how to build the package. If I try and use conda-build, it attempts to download the entire package from github and then hits a 404 error. Following this, `conda install --use-local` doesn't work -- I'm not sure if the build failed, or I'm doing the install wrong.

If I try and use setup.py, I encounter the error `Unable to deduce type parameters for K (
const K, I *, const I) noexcept nogil given (npy_intp, uint256_t *, uint256_t &)` during Cythonisation.

**Comment by mgbukov** [comment]
check out the new developer install which makes it easier to contribute to quspin ;)

**Comment by jaredjeya** [comment]
I'll take a look!

**Comment by jaredjeya** [comment]
I've just tried and run into a problem, #717

**Comment by jaredjeya** [comment]
I fixed what I thought was the issue in `_format_output` (and I'm certain that fix has no side-effects), but another one popped up in another part of the code:

```python
rv_cb_arr is NULL
Call-back cb_fcn_in___user__routines failed.
Traceback (most recent call last):
  File "test_quspin_evolve.py", line 15, in <module>
    iter_states = H.evolve(states, 0.0, times, stack_state=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\QuSpin-workspace\QuSpin\src\quspin\operators\hamiltonian_core.py", line 1651, in evolve
    return evolve(*evolve_args, **evolve_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\QuSpin-workspace\QuSpin\src\quspin\tools\evolution.py", line 351, in evolve
    return _evolve_list(solver, v0, t0, times, verbose, *output_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\QuSpin-workspace\QuSpin\src\quspin\tools\evolution.py", line 411, in _evolve_list
    solver.integrate(t)
  File "...\scipy\integrate\_ode.py", line 431, in integrate
    self._y, self.t = mth(self.f, self.jac or (lambda: None),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\scipy\integrate\_ode.py", line 1176, in run
    x, y, iwork, istate = self.runner(*((f, t0, y0, t1) +
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many axes: 2 (effrank=2), expected rank=1
```

I've tried to debug this, but since this it's happening in Scipy's Fortran code, and the error message is very unspecific about *what* has too many axes, I have no idea if this is an upstream bug, or something being passed incorrectly to the function. It still only happens with `stack_state=True`

The absolute minimum code needed to re-create this bug is:

```python
import numpy as np

from quspin.operators import hamiltonian
from quspin.basis import spin_basis_1d
from scipy.integrate._ode import dopri5
from scipy.integrate._dop import dopri5 as dop_dopri5

N = 6
n_state = 10
times = np.linspace(0, 1, 11)

basis = spin_basis_1d(N)
static = [["x", [[1.0, i] for i in range(N)]]]
H = hamiltonian(static, [], basis=basis, dtype=np.float64)

states = np.random.random(size=(basis.Ns, n_state))
states /= np.linalg.norm(states, axis=0, keepdims=True)

# iter_states = evolve(H, v0=states, t0=0.0, times=times, stack_state=True)
v1 = states.copy().ravel()
v0 = np.zeros(2 * states.size, dtype=v1.real.dtype)
v0[:states.size] = v1.real
v0[states.size:] = v1.imag
del v1
f_params = (np.zeros((states.shape[0] * 2,) + states.shape[1:], dtype=np.float64, order="C"),)
this_ode = dopri5()
this_ode.reset(len(v0), False)
x, y, iwork, istate = dop_dopri5(H._hamiltonian__SO_real, 0, v0, 0.1, *tuple(this_ode.call_args), f_params)
```
