### ISSUE TITLE
Manual installation fails to compile Cython file general_basis_core.pyx

### ISSUE THREAD

**Issue by wilf-phasecraft** [QuSpin/QuSpin#677]
I am following the "Installing Manually" instructions [given here ](https://quspin.github.io/QuSpin/Installation.html). I have installed all of the requirements listed on the same page (see below)

```
(.venv) wilfrid@Wilfrids-MBP quspin % pip list --local                                
Package            Version
------------------ -----------
blurhash           1.1.4
boost              0.1
certifi            2024.2.2
charset-normalizer 3.3.2
Cython             3.0.10
decorator          5.1.1
dill               0.3.8
gmpy2              2.1.5
idna               3.7
importlib_metadata 7.1.0
joblib             1.4.0
llvmlite           0.41.1
Mastodon.py        1.8.1
numba              0.58.1
numexpr            2.8.6
numpy              1.24.4
pip                23.0.1
python-dateutil    2.9.0.post0
python-magic       0.4.27
requests           2.31.0
scipy              1.10.1
setuptools         56.0.0
six                1.16.0
SQLAlchemy         2.0.29
typing_extensions  4.11.0
urllib3            2.2.1
zipp               3.18.1

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
```

When I then run `python setup.py install --default-compiler-flags` from the `path/to/QuSpin/quspin` directory I encounter the following error relating the the Cython compilation

```
[1/7] Cythonizing /Users/wilfrid/Documents/Projects/QEDFT/QuSpin/quspin/basis/basis_general/_basis_general_core/boson_core.pyx

Error compiling Cython file:
------------------------------------------------------------
...
                    raise TypeError("attempting to use real type for complex elements.")

                with nogil:
                    for i in range(Ns):
                        c[i] *= sign[i]
                        indices[i] = <npy_intp>rep_position(Ns_full,basis_pcon,basis[i])
                                                           ^
------------------------------------------------------------

basis/basis_general/_basis_general_core/source/general_basis_core.pyx:128:59: Unable to deduce type parameters for K (const K, I *, const I) noexcept nogil given (npy_intp, uint256_t *, uint256_t &)
```

This error occurs quite a few times with the traceback

```
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    setup(**configuration(top_path='').todict())
  File "setup.py", line 4, in configuration
    config.add_subpackage('basis')
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1050, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1016, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 958, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "./basis/setup.py", line 44, in configuration
    config.add_subpackage('basis_general')
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1050, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1016, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 958, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "basis/basis_general/setup.py", line 5, in configuration
    config.add_subpackage('_basis_general_core')
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1050, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1016, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 958, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "basis/basis_general/_basis_general_core/setup.py", line 44, in configuration
    cython_files()
  File "basis/basis_general/_basis_general_core/setup.py", line 36, in cython_files
    cythonize(cython_src,include_path=get_include_dirs())
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/Users/wilfrid/Documents/Projects/QEDFT/.venv/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /Users/wilfrid/Documents/Projects/QEDFT/QuSpin/quspin/basis/basis_general/_basis_general_core/boson_core.pyx
```

Not really familiar with Cython, so not sure if this is a bug in QuSpin, Cython, or my installation procedure.

**Comment by mgbukov** [comment]
check out the new manual installation for quspin 1.0.0 onwards.

closing this for now
