### ISSUE TITLE
AttributeError: type object 'Record' has no attribute 'make_c_struct'

### ISSUE THREAD

**Issue by YouXiaoAssignment** [QuSpin/QuSpin#686]
I'm installing QuSpin 0.3.7 on a cluster, and there're several things I notice:

i) QuSpin is automatically installed on Python 3.6 (I think it automatically install Python 3.6 when installing QuSpin), whereas in the cluster there're only options of 3.10 (available module) . Would there be any conflict? In fact, if I module load Python 3.10 and runs a script, it reports ` No module named 'quspin' ` error

ii) The installation process seems to want to change Mamba environmen, I have no idea whether this would lead to iii)
```
$ mamba install -c weinbe58 quspin

Looking for: ['quspin']

error    libmamba Could not open lockfile '/n/sw/Mambaforge-23.11.0-0/pkgs/cache/cache.lock'
error    libmamba Removing lock file '/n/sw/Mambaforge-23.11.0-0/pkgs/cache/cache.lock' failed
    You may need to remove it manually
error    libmamba Could not open lockfile '/n/sw/Mambaforge-23.11.0-0/pkgs/cache/cache.lock'
error    libmamba Removing lock file '/n/sw/Mambaforge-23.11.0-0/pkgs/cache/cache.lock' failed
    You may need to remove it manually
weinbe58/noarch                                               No change
weinbe58/linux-64                                             No change
conda-forge/noarch                                  15.2MB @  29.3MB/s  0.5s
conda-forge/linux-64                                35.7MB @  43.7MB/s  0.9s

Pinned packages:
  - python 3.6.*

```
iii) When running a script importing QuSpin on Python 3.6 (after the installation), there is an error occurs as,
```
Traceback (most recent call last):
  File "spinor.py", line 2, in <module>
    from quspin.operators import hamiltonian,quantum_LinearOperator # Hamiltonians and operators
  File "/n/home02/pipilu/.conda/envs/quspin/lib/python3.6/site-packages/quspin/__init__.py", line 3, in <module>
    from . import operators
  File "/n/home02/pipilu/.conda/envs/quspin/lib/python3.6/site-packages/quspin/operators/__init__.py", line 54, in <module>
    from .quantum_operator_core import *
  File "/n/home02/pipilu/.conda/envs/quspin/lib/python3.6/site-packages/quspin/operators/quantum_operator_core.py", line 3, in <module>
    from ..basis import spin_basis_1d as _default_basis
  File "/n/home02/pipilu/.conda/envs/quspin/lib/python3.6/site-packages/quspin/basis/__init__.py", line 136, in <module>
    from quspin.basis.user import *
  File "/n/home02/pipilu/.conda/envs/quspin/lib/python3.6/site-packages/quspin/basis/user.py", line 1, in <module>
    from .basis_general.base_user import (user_basis,map_sig_32,op_sig_32,next_state_sig_32,count_particles_sig_32,
  File "/n/home02/pipilu/.conda/envs/quspin/lib/python3.6/site-packages/quspin/basis/basis_general/base_user.py", line 19, in <module>
    op_results_32 = types.Record.make_c_struct([
AttributeError: type object 'Record' has no attribute 'make_c_struct'

```

Is this caused by version conflict?

**Comment by mgbukov** [comment]
We do have a precompiled qyspin 0.3.7 for py3.10, see here:

https://anaconda.org/weinbe58/quspin/files

Why don't you enforce the quspin and python versions in conda install?

For each python version, there's a different quspin installation you have
to do.

Marín

**Comment by YouXiaoAssignment** [comment]
I see, thanks for quick response! :)
